version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(github-actions)"
  - package-ecosystem: npm
    directory: website/
    schedule:
      interval: daily
      time: "15:00"
    allow:
      - dependency-name: "@genspectrum/dashboard-components"
    commit-message:
      prefix: "chore(website)"
    target-branch: "main"
  - package-ecosystem: npm
    directory: website/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(website)"
  - package-ecosystem: gradle
    directory: backend/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(backend)"
