services:
  website:
    image: ghcr.io/genspectrum/dashboards/website:${WEBSITE_TAG}
    init: true
    platform: linux/amd64
    ports:
      - "127.0.0.1:4321:4321"
    environment:
      BACKEND_URL: http://backend:8080
      DASHBOARDS_ENVIRONMENT: dashboards-prod
      GITHUB_CLIENT_ID: "dummy"
      GITHUB_CLIENT_SECRET: "dummy"
      AUTH_SECRET: "e2e-test-auth-secret-do-not-use-in-production"

  backend:
    image: ghcr.io/genspectrum/dashboards/backend:${BACKEND_TAG}
    platform: linux/amd64
    ports:
      - "127.0.0.1:9021:8080"
    depends_on:
      - database
    command:
      - --spring.datasource.url=jdbc:postgresql://database:5432/dashboards-backend-db
      - --spring.datasource.username=postgres
      - --spring.datasource.password=unsecure
      - --spring.profiles.active=dashboards-prod

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unsecure
      POSTGRES_DB: dashboards-backend-db
    ports:
      - "127.0.0.1:9022:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  example-data-seeder:
    image: ghcr.io/genspectrum/dashboards/example-data-seeder:${SEEDER_TAG}
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080
    restart: "no"

volumes:
  database-data:
