services:
  website:
    image: ghcr.io/genspectrum/dashboards/website:${WEBSITE_TAG}
    ports:
      - "127.0.0.1:9020:4321"
    volumes:
      - type: bind
        source: ./website/tests/config
        target: /config
        read_only: true
  
  backend:
    image: ghcr.io/genspectrum/dashboards/backend:${BACKEND_TAG}
    ports:
      - "127.0.0.1:9021:8080"
    depends_on:
      - database
    command:
      - --spring.datasource.url=jdbc:postgresql://database:5432/subscriptions
      - --spring.datasource.username=postgres
      - --spring.datasource.password=unsecure
        
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: unsecure
      POSTGRES_DB: subscriptions
    ports:
      - "127.0.0.1:9022:5432"
      