# Dockerfile for the website
# This is here so that the build context can access the backend config files
FROM node:22.4-alpine AS base
WORKDIR /app

COPY website/package.json website/package-lock.json website/patches ./

FROM base AS prod-deps
RUN npm clean-install --omit=dev

FROM base AS build
RUN npm clean-install
COPY website/.env.docker .env
COPY website .
RUN npm run build -- --host

FROM base AS runtime
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY backend/src/main/resources /config

EXPOSE 4321

CMD ["node", "./dist/server/entry.mjs"]
