@startuml
title "GenSpectrum - Level 1"

skinparam component<<external>> {
    BorderStyle dashed
}

actor User as user
component "NCBI" <<external>> as ncbi
component "GitHub" <<external>> as github
component "Pathoplexus" <<external>> as pathoplexus
cloud "Various external mutation information" as vemi

node "GenSpectrum" {
    component Website as website
    component Backend as backend
    component "Collection Seeder" as seeder
    database Database as db
    component Loculus as loculus
}

user -r-> website : "Interact"
website -d-> backend : "Users, subscriptions, collections, config"
backend -d-> db : "Persist"
website -r-> loculus : "Query genomic data"
seeder -u-> backend : "Seed collections"
loculus -r-> ncbi : "Pull data"
seeder -r-> vemi : "Pull data"
website -r-> github : "Authenticate"
website -r-> pathoplexus : "Query genomic data"
db -[hidden]-> seeder

@enduml
