name: Backend

on: [ push ]

env:
  DOCKER_IMAGE_NAME: ghcr.io/genspectrum/dashboards/backend

jobs:
  tests:
    name: Check format, lint and run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Tests
        run: ./gradlew test

      - name: Check Format And Lint
        run: ./gradlew ktlintCheck

  dockerImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: dockerMetadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          cache-from: type=gha,scope=dashboards-${{ github.ref }}
          cache-to: type=gha,mode=max,scope=dashboards-${{ github.ref }}
          platforms: ${{ github.ref == 'refs/heads/main' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: true
