name: Backend

on: [ push ]

jobs:
  tests:
    name: Check format, lint and run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Tests
        run: ./gradlew test

      - name: Check Format And Lint
        run: ./gradlew ktlintCheck
