name: Create PR to Update Prod

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create Pull Request to prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr list --base prod --head main --state open --json number | jq -e '. | length > 0'; then
            echo "PR to update prod from main already exists - skipping creation"
          else
            body="This pull request updates the \`prod\` branch with the latest changes from the \`main\` branch. **Do not squash-merge** this PR."
            gh pr create --base prod --head main --title "Update prod from main" --body "$body"
          fi
